### ISSUE TITLE
Import quickbuy from hypixel

### ISSUE THREAD

**Issue by ARDragssss** [boiscljo/SBA#11]
its something really simple yet really effective. You can just click on a certain item and your quickbuy from hypixel gets imported.

**Comment by ARDragssss** [comment]
and please make the whole page customizable, just like the hypixel shop.

**Comment by boiscljo** [comment]
> its something really simple yet really effective. You can just click on a certain item and your quickbuy from hypixel gets imported.

Stop making Issues for a matter that is IMPOSSIBLE as Hypixel doesn't have an API to get that info
