### ISSUE TITLE
No error just went down (Store create)

### ISSUE THREAD

**Issue by Luke22076** [boiscljo/SBA#15]
When i want to make an shop npc, my server just go down... No errors only my server is going down... Please help me.
Using Screaming Bedwars + SBA on Java 11 on 1.19.4 Paper

The last message i am getting is, that the NPC is created. But then the server is down...

**Comment by boiscljo** [comment]
You encountered an issue that cannot be fixed by SBA, the server actually didn't go down, but your proxy Bungeecord seems to not like the NPC, you can disable them ir use Waterfall(a fork of bungee that doesn't have the issue).
