### ISSUE TITLE
Server crash Error

### ISSUE THREAD

**Issue by Llopeando** [boiscljo/SBA#16]
Hi there!
For any reason, an error appeared in console spamming it and kicking all of my users.
I don't know how this error was generated, here is the full error log:
https://mcpaste.io/2ffb643749e48a11

**Comment by boiscljo** [comment]
One of your tier in the config doesn't have the -I -II for the level of the tier(-1 means it could not find the -) do you have somethinf like Emerald: 0 instead of Emerald-I: 0

**Comment by Llopeando** [comment]
This is my current sbaconfig.yml, I don't see something strange in a first look.
https://pastebin.com/m0zp8Z3Q

**Comment by boiscljo** [comment]
Gold and Iron should be Gold-I and Iron-I

**Comment by Llopeando** [comment]
Changed! It should be fixed now then, thank you!
_Closing issue as it has been resolved_
