### ISSUE TITLE
shops arent reloaded

### ISSUE THREAD

**Issue by HierarchyMan** [boiscljo/SBA#18]
i put custom values in my upgrades shop
i restarted the server ensured everything was saved but the shop prices just wont update

**Comment by HierarchyMan** [comment]
update the entire shop wont reload

**Comment by boiscljo** [comment]
1. Did you edit the shops in the plugins/Bedwars/upgradeShop.yml ?
2. What value did you change, if it's the price of sharpness and such, those are in the main sbaconfig.yml
3. make sure you don't have the shop in plugins/SBA/shops/... this is a legacy folder and the one in bedwars are used instead

Check your yml is valid as the plugin might revert to default if your shop yml is invalid

**Comment by HierarchyMan** [comment]
> 1. Did you edit the shops in the plugins/Bedwars/upgradeShop.yml ?
> 2. What value did you change, if it's the price of sharpness and such, those are in the main sbaconfig.yml
> 3. make sure you don't have the shop in plugins/SBA/shops/... this is a legacy folder and the one in bedwars are used instead
> 
> Check your yml is valid as the plugin might revert to default if your shop yml is invalid

The rows did change I was just confused about the price not changing
Thanks for specifying that the prices should be changed in sbaconfig.yml
My issue is now resolved
