### ISSUE TITLE
Chat Level prefix conflicting with LuckPerms.

### ISSUE THREAD

**Issue by C0rupted** [boiscljo/SBA#19]
I have luckperms installed alongside SBA, however, even after disabling the functions in SBA's config, SBA still overrides LuckPerms when it comes to display names. Anyway to fix this?

**Comment by boiscljo** [comment]
Not a SBA bug, a config issue on your end, SBA doesn't override display name, it override chat, just add prefix to the chat format in SBA config and displayname instead of plyer name (with papi placeholders).
