### ISSUE TITLE
name-provider bug

### ISSUE THREAD

**Issue by KuroiNekOo** [boiscljo/SBA#22]
When I want to put the team color with the pseudo, it only displays the pseudo but not the color.

![image](https://github.com/boiscljo/SBA/assets/65861828/9e360874-3dc7-43b1-b86f-d2510c9e1702)

![image](https://github.com/boiscljo/SBA/assets/65861828/c87d098b-1064-46cc-ad6c-97225230620d)

**Comment by boiscljo** [comment]
Name provider is supposed to be PAPI placeholders to provide the name for the health below the name, it is not meant for colors.

**Comment by KuroiNekOo** [comment]
is there a way to put the player nickname in color?

**Comment by boiscljo** [comment]
You need 3rd party plugin for that, all displayed text in the plugin uses the player display name; find a plugin that changes their display name. For the nametag, use a plugin such as TAB.
