### ISSUE TITLE
Tier limits bug

### ISSUE THREAD

**Issue by KuroiNekOo** [boiscljo/SBA#23]
Hi, there,

Another problem, I've set Spawn limits regarding the diamond and emerald spawner depending on the Tier but sometimes it doesn't work, even very often the limit is exceeded and I don't understand why.

For example, in Tier 1, I set 4
Tier 2, I set 6 and Tier 3, I set 8

Sometimes on Tier 2, it'll go Spawn to 8 or 10 or even 12 diamonds.

**Comment by boiscljo** [comment]
SBA changes the limit, but Bedwars enforces it, if it goes above the limit, then it's a bedwars bug.

**Comment by KuroiNekOo** [comment]
Okay, thank :)
