### ISSUE TITLE
Timer scoreboard and game bedwars bug

### ISSUE THREAD

**Issue by KuroiNekOo** [boiscljo/SBA#24]
Hi

I have a bug with the game timer, which means that my game ends for no reason when it should last 2 hours in total.

Now the game suddenly ends at any time.

I didn't have this bug when I wasn't using the SBA addon. The game used to last 2 hours

![image](https://github.com/boiscljo/SBA/assets/65861828/6d08cf9c-9e01-4845-9eeb-6397858d0315)

Rec complet :
Number 1 : https://streamable.com/ih5i2z
Number 2 : https://streamable.com/acujlm

Even after a complete reinstall of the server in 1.19.4 and a reset to 0 of the SBA and BW configuration, it still bugs, so it's not due to the configuration.

**Comment by boiscljo** [comment]
Is this still happening?

**Comment by KuroiNekOo** [comment]
yes, I'm using the SBA 1.5.10 addon

**Comment by KuroiNekOo** [comment]
I'll use the new version to check when I get home from work.

**Comment by KuroiNekOo** [comment]
![Capture d’écran 2023-09-15 à 14 50 26](https://github.com/boiscljo/SBA/assets/65861828/3183147e-5b3a-4218-990b-62faffd6bdae)

**Comment by KuroiNekOo** [comment]
its good : https://github.com/boiscljo/SBA/releases/tag/1.5.11-dev2-pr29.c3de060%22
