### ISSUE TITLE
BUG: message + minertrap + skip

### ISSUE THREAD

**Issue by KuroiNekOo** [boiscljo/SBA#25]
The blindtrap and minertrap have the same effect, cecity III for 3 seconds, I think the trap has just been copied and pasted but the mining fatigue effect has not been implemented for the minertrap, how do I correct this?

Nowhere in the configuration did I find the possibility of changing the trap effect.
![image](https://github.com/boiscljo/SBA/assets/65861828/63c1e031-dc83-46e8-8790-710593534190)

Another thing: the minertrap can be bought indefinitely, but it will only be activated once, so if someone spams to buy it, they'll lose their diamonds and the trap will only work once.

With the other traps, they are limited to 1 purchase, but the minertrap is not.
![Capture d’écran 2023-09-12 à 13 23 54](https://github.com/boiscljo/SBA/assets/65861828/4f466dd5-45ed-4344-9173-35b9796db9e7)

This is the message displayed to the player who triggers the minertrap.

It's the same as for the blindtrap trap
![image](https://github.com/boiscljo/SBA/assets/65861828/58a68e9c-61df-4f18-a8c7-61309d1800bf)

And the team name is wrong, it's our own team's name when it should be the opposing team's name.

**Comment by boiscljo** [comment]
Check this release and tell me if it fixes it https://github.com/boiscljo/SBA/releases/tag/1.5.11-dev1-issue25.40075a8%22

**Comment by KuroiNekOo** [comment]
Its good, thank :)
