### ISSUE TITLE
Link does not exist...

### ISSUE THREAD

**Issue by NopeProsOnly** [boiscljo/SBA#3]
![image](https://user-images.githubusercontent.com/78925970/209392677-b7b6cfd7-1822-482e-8489-8e638c328171.png)
Hey! Update the link to a working one.

**Comment by NopeProsOnly** [comment]
Check it out yourself with https://github.com/boiscljo/SBA/blob/release/plugin/src/main/resources/config.yml

**Comment by boiscljo** [comment]
I instead removed the link as the info from it is outdated. SBA doesn't provide info for bw config anymore as it causes issues with bedwars.
