### ISSUE TITLE
1.20.2 not working. Most likely due to plugin version.

### ISSUE THREAD

**Issue by MassaHex** [boiscljo/SBA#32]
# Problem
When using the SBA hypixelfy plugin an error occurs. None of my players can join the server until this is fixed. The error is displayed the console as ```01.10 02:31:49 [Server] [WARN] java.lang.NullPointerException: Failed to find player channel!```. Now this may seem like nothing much but it really is. When the players join they see a screen that says "Failed to inject! Please rejoin!".

**Comment by boiscljo** [comment]
I'm waiting for SLib (dependancy) to update to 1.20.2, if you check the page it says 1.9.4 to 1.20.1 not 1.20.2, it will be supported when SLib updates.

**Comment by boiscljo** [comment]
Latest release support 1.20.2
