### ISSUE TITLE
Generator upgrades and PAPI expansion for Bungee

### ISSUE THREAD

**Issue by leeteral** [boiscljo/SBA#40]
Hi there,

First of all, the default generator upgrades (diamond/emerald) contain a `-` in the scoreboard and spaces will cause the scoreboard to not be displayed at all. However, `Diamond-I`, `Emerald-II`, etc. look ugly. Is there any way to have a space instead?

Secondly, it would be really useful if there was a PlaceholderAPI expansion for BungeeCord servers. For example, let's say that there's 2 BedWars servers and each server has a single arena running. We would want our players, from the lobby, to see if there's a game running on the servers and other game statistics without having to join where the arena is. _Not sure if that's possible though, maybe could be saved to a MySQL database?_

**Comment by boiscljo** [comment]
#For the placeholder, ask the Bedwars team, they are the one storing the statistics, SBA just show Bedwars info. 

For the emerald dash, it's not possible yet.

**Comment by leeteral** [comment]
Isn't it possible for SBA to have an expansion? Like at least if the game is running and the alive players.. Not sure how I can contact the plugin developers and how long it's gonna take for them to respond.

**Comment by boiscljo** [comment]
SBA cannot access mysql from bedwars without bedwars. And SBA has no plan and won't support anything related to bungee/velocity. https://github.com/ScreamingSandals/Bedwars

**Comment by leeteral** [comment]
Thank you for your response, I've submitted a feature request on the BedWars repository
