### ISSUE TITLE
GamesInv NPC

### ISSUE THREAD

**Issue by Bensonheimer992** [boiscljo/SBA#41]
can anyone help my with this : [18:50:59 ERROR]: [SBA] Unable to retreive skin of Arokat: NULL

**Comment by boiscljo** [comment]
Could you use the SBW discord for support as this just seems to be using an invalid mojang name for the skin.

**Comment by Bensonheimer992** [comment]
You now all mojangs accounts got deleted there are only microsoft accounts now

**Comment by Bensonheimer992** [comment]
@boiscljo

**Comment by boiscljo** [comment]
Even if it's Microsoft accounts, the Minecraft skin server is still Mojang's. It's not used for login or anything; it searches Minecraft accounts by name and retrieves their skin. 

@Bensonheimer992 
For some reason the MOJANG API returned no skin for the player when you ran the command, it queried the following links:
https://api.mojang.com/users/profiles/minecraft/AroKat
https://sessionserver.mojang.com/session/minecraft/profile/f67397c0e83e4921857d727fe235779e

Plus, skin retrieval is done via ScreamingLibs, SBA just calls the library, if there are any issues https://github.com/ScreamingSandals/ScreamingLib/blob/ver/2.0.x/extensions/npc/common/src/main/java/org/screamingsandals/lib/npc/skin/NPCSkin.java
