### ISSUE TITLE
Crash when spawning store NPC

### ISSUE THREAD

**Issue by jstinson5640** [boiscljo/SBA#47]
![Screenshot 2024-01-21 201751](https://github.com/boiscljo/SBA/assets/78497808/40e8756b-2c8f-4318-b86c-68f24224395b)

When I add the Store NPC, my server crashes and I cannot rejoin without resetting the server. Nothing appears in my server log relating to this bug.

SBA Version: Most Recent
ScreamingBedwars: 0.20.0
Minecraft Version: 1.20.4

**Comment by Misat11** [comment]
The latest version of SBA still does not support 1.20.4. @boiscljo will release a new version soon.

There's no version of ScreamingBedWars like 0.20.0, the latest released version is 0.2.31.

**Comment by jstinson5640** [comment]
Thanks for the comment.

I made a typo on accident, the screaming bedwars version I’m on is 0.2.20

Thanks for the update!

**Comment by boiscljo** [comment]
Build should be released for it. But bedwars 0.2.20, that's too old, you need to update bedwars as SBA is probably incompatible with such  a old bedwars version. Use 0.2.29 at minimum or 0.2.31 (latest) ideally.
