### ISSUE TITLE
Scoreboards keep resetting 

### ISSUE THREAD

**Issue by Agron12MC** [boiscljo/SBA#54]
Whenever I play the game and stop the server after inactivity. But when I start it back my stats and leaderboard are resetting. Is there anyway to retain the data. The server is running on Paper 1.20.4 Java 17
![171326863295962109812023685693](https://github.com/boiscljo/SBA/assets/167202010/a3303f06-0c8d-4198-8fc1-85b808b0a77e)
Also is there any way to customise the scoreboard and tablets pls do let me know. Thanks

**Comment by boiscljo** [comment]
Stats are stored by Bedwars not SBA. Check with them on discord why it resets. To cuztimise modify language_en.yml
