### ISSUE TITLE
My lobby scoreboards keep resetting

### ISSUE THREAD

**Issue by Agron12MC** [boiscljo/SBA#55]
SO I did /sba setlobby and then joined a games. after the game was completed the lobby scoreboard and tablist were missing.
So i had to do /sba setlobby again. But when i join the games it again resets it back. So i have to keep spamming /sba setlobby everytime a game has been completed. Is there a fix for this?

Im using 1.20.4 and Atenros

**Comment by boiscljo** [comment]
Can you send plugin list to see if there is an infompribility, seems some other plugin is preventing the default handling on scoreboard.

**Comment by Agron12MC** [comment]
> Can you send plugin list to see if there is an infompribility, seems some other plugin is preventing the default handling on scoreboard.

The only plugins on the server is SBA, Bedwars and World Edit...

**Comment by boiscljo** [comment]
Then I know the issue and it won't be fixed. Lobby world CANNOT be the same world as the maps. It breaks lobby. Install something like Multiverse and have the games in a different world than the lobby.
