### ISSUE TITLE
Scoreboard invisible after death

### ISSUE THREAD

**Issue by dovisp** [boiscljo/SBA#56]
All of this is happening in match. I don't see anything on console or anywhere else.

**Comment by boiscljo** [comment]
Seems another plugin might be trying to put their own scoreboard causing the SBA one to break. If possible please go on the discord for support until its a confirmed issue. https://discord.gg/tQ44VUek

**Comment by dovisp** [comment]
Sorry, but which channel?

**Comment by boiscljo** [comment]
Support or community-support

**Comment by boiscljo** [comment]
https://discord.gg/tQ44VUek
sorry wrong server

**Comment by dovisp** [comment]
HealthBar-Reloaded was the problem. Closing.
