### ISSUE TITLE
Forge not working properly.

### ISSUE THREAD

**Issue by NopeProsOnly** [boiscljo/SBA#6]
You can upgrade forge infinitely, you can't put a limit on it... it takes the items required and says that it upgrades, but i can't tell a difference.

**Comment by NopeProsOnly** [comment]
https://paste.gg/p/anonymous/3e81705ba08e438087cd34c89f5932a7
Config

**Comment by NopeProsOnly** [comment]
I don't know if this means anything important... `Since SBA 1.5.7, the shops are moved into plugins/BedWars/...` <-- What would I do about this?

**Comment by boiscljo** [comment]
> You can upgrade forge infinitely, you can't put a limit on it... it takes the items required and says that it upgrades, but i can't tell a difference.

It increase the amount of ressources spawned every time. The limit is currently only implemented on the spawnwer but it is purchasable infinitly. Not enough time in a day to implement it soon.
