### ISSUE TITLE
Player in tablist not work

### ISSUE THREAD

**Issue by TechnoTypist** [boiscljo/SBA#63]
So I watched a video on this plugin and it showed that on the tablist It was supposed to have a letter in the color of the team and the letter of the team they were playing on before the player's name as a prefix, and this works for the chat but for some reason it does not work for the tab for me. I have removed all prefixes and stuff from the luckperms and it still does not work. Any I idea why? because without it is very hard to tell who is on what team.

**Comment by boiscljo** [comment]
Videos were for V1.4... this feature didn't work since 1.5 and less than 5% of users used it. They can just use placeholders and something like TAB to have it the way they want. Way more customization

**Comment by TechnoTypist** [comment]
How do I do that? Also, is there any way that you could make it so that the npc act like real players's? They go to the ores and spend them to buy stuff from the shop, and they can actually bridge and break beds and stuff? Also is there any way you could make them join if not enough player's join the game in like 5 minutes, or at least make it execute a command if nobody joins in 5 minutes?

**Comment by boiscljo** [comment]
There is an experimental settings in the AI to use shop. They ahould be able to bridge and they sometime do. But generally the gap needs to be max 4-5 blocks otherwise it can't pathfind.

**Comment by boiscljo** [comment]
SBA switched to LTS as I don't have time to code. So AI won't improve and only bugs that have bo workaround will have fixes. No new features. For tablist, the plugin TAB allow you to change the player's prefix and suffix in tablist you could use placeholders from bedwars itself, check their discord for the FAQ and list. With that you can get exactly what you want.

**Comment by TechnoTypist** [comment]
Yes, I was using the tab plugin beforehand but it would glitch with the built in bedwars one. What is their discord? Also is there any way to have the countdown for the start of the game to be on the bossbar and the xp bar? And is there ea command to remove all player's from their games (Shut down the plugin) so I can have my auto restart plugin do that before the restart comes, because if not it will glitch and the player's will keep the items they had in their inventories when they come back after.

**Comment by TechnoTypist** [comment]
Also, how do i use the TAB plugin to change prefixes without messing with the tab? I would like to use the built in bedwars tab, but only change the prefixes, can I get support for that in their discord?

**Comment by boiscljo** [comment]
https://discord.gg/WvQQjnab

Community support or a ticket would be better than a github issue

**Comment by TechnoTypist** [comment]
Also, how do I make the max that a generator can hold to set to unlimited?

**Comment by TechnoTypist** [comment]
Also, different placeholders not from the bedwars plugin do not seem to work in the lobby tab (or maybe any tab idk).
