### ISSUE TITLE
Adding SBA the sugarcane in the shop.yml becomes ineffective

### ISSUE THREAD

**Issue by Chaostarts** [boiscljo/SBA#71]
Bedwars version 0.2.33.1
SBA 1.5.13.1
Server version spigot-1.8.8
After adding SPA, the sugarcane in the store becomes ineffective
I have tried multiple IDs, but none of them, such as SUGAR_CANE REEDS, SUGAR_CANES, can be used. They all display as Air

**Comment by boiscljo** [comment]
It should probably be SUGARCANE withiut a space, but I do not know on such a old minecraft version. You should ask on the discord https://discord.gg/XNcMVvamqz. Shop is handled by ScreamingLibs (A library by the bedwars dev, as such they know better than me for items)

**Comment by Chaostarts** [comment]
> It should probably be SUGARCANE withiut a space, but I do not know on such a old minecraft version. You should ask on the discord https://discord.gg/XNcMVvamqz. Shop is handled by ScreamingLibs (A library by the bedwars dev, as such they know better than me for items)

No, this still doesn't work, and it appears after adding the SBA plugin. Deleting SBA will display it normally

**Comment by Misat11** [comment]
![obrazek](https://github.com/user-attachments/assets/18ad8115-78b8-46dc-ad02-82321a3abe32)
Have you tried `sugar_cane` with underscore, as listed on Minecraft Wiki?

**Comment by Chaostarts** [comment]
> ![obrazek](https://private-user-images.githubusercontent.com/20199703/349914761-18ad8115-78b8-46dc-ad02-82321a3abe32.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzMDEyMTksIm5iZiI6MTcyMTMwMDkxOSwicGF0aCI6Ii8yMDE5OTcwMy8zNDk5MTQ3NjEtMThhZDgxMTUtNzhiOC00NmRjLWFkMDItODIzMjFhM2FiZTMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE4VDExMDgzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhNTRjZDAwMTFlZGFhYzBhYzBkYWExOThhNGJhZmE4NWYwYjc2YWQyNWU3ZWFjZmNmZTA2OTBjM2Q0ZGZmMWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Y8yVbP2W4mtF-IswCy4l7_KUDldTuBkr3yOZwKEDVlo) Have you tried `sugar_cane` with underscore, as listed on Minecraft Wiki?

Yes I tried

**Comment by Chaostarts** [comment]
I solved by adding legacy/ before the sugar_cane
