### ISSUE TITLE
GameInv NPC 

### ISSUE THREAD

**Issue by BlueDragon4251** [boiscljo/SBA#77]
The NNPC says Game not Found what schould i do?

**Comment by Misat11** [comment]
Run `/sba generate`

**Comment by BlueDragon4251** [comment]
everythingswork but not the  npc for the mega maps

**Comment by BlueDragon4251** [comment]
By the way, I still get this error message, but I have already updated the plugin

![image](https://github.com/user-attachments/assets/8aacdc88-a01d-444e-8be4-ade085879bb2)

**Comment by boiscljo** [comment]
> everythingswork but not the  npc for the mega maps

since mega map is not a standard one you need do manually add it:

/sba generate MEGA MAP1 MAP2....

using it without argument only fill up solo/duo/triples/squad

**Comment by boiscljo** [comment]
> By the way, I still get this error message, but I have already updated the plugin
> 
> 
> 
> ![image](https://github.com/user-attachments/assets/8aacdc88-a01d-444e-8be4-ade085879bb2)
> 
> 

I would need to release a new update to fix that, since plugin has an extra text in the version number.

**Comment by BlueDragon4251** [comment]
What  schould i do for this title?  
![image](https://github.com/user-attachments/assets/2e775d63-bcc4-490f-ab9a-f21d832dcebe)

**Comment by boiscljo** [comment]
> What  schould i do for this title?  
> 
> ![image](https://github.com/user-attachments/assets/2e775d63-bcc4-490f-ab9a-f21d832dcebe)
> 
> 

Add the mega prefix to the language file(language_en.yml)(same way as solo prefix etc...)

**Comment by BlueDragon4251** [comment]
thank you thats all
