### ISSUE TITLE
Can we change the content of config and make it effective? 

### ISSUE THREAD

**Issue by MoXiaoXi233** [boiscljo/SBA#79]
Instead of overwriting sbaconfig.yml every time it starts
I want to change the skin of the villagers:)

**Comment by boiscljo** [comment]
The file only overwrite itself if it's not a valid YML, please check with a YML validator.

**Comment by MoXiaoXi233** [comment]
> The file only overwrite itself if it's not a valid YML, please check with a YML validator.

Oh, it's working! Thank you very much for correcting my mistake.
