### ISSUE TITLE
1.8 support

### ISSUE THREAD

**Issue by 42willow** [boiscljo/SBA#8]

**Comment by boiscljo** [comment]
We're waiting on ScreamingLib see https://github.com/ScreamingSandals/ScreamingLib to add 1.8 support as it's the reason why SBA doesn't support it.

**Comment by boiscljo** [comment]
https://github.com/boiscljo/SBA/releases/tag/1.5.11-dev4-pr28.d84e070%22

This build should have partial 1.8 support. NPC will misbehave with ViaVersion for the moment being, the rest seems in working state.

**Comment by boiscljo** [comment]
Latest release support 1.8.8 (Java 11 required)
