### ISSUE TITLE
Translation Error

### ISSUE THREAD

**Issue by ChanellYT** [boiscljo/SBA#81]
It is not possible to translate the plugin, because when it is translated it stops working!

**Comment by boiscljo** [comment]
Could you provide with the translation file you used? It is entirely possible to translate the plugin, however if the yml file gets altered in the amount of spacing or removing entries it might causes issues. Checking your file should allow us to fund the actual issue

**Comment by boiscljo** [comment]
Closing as OP is not answering the requested information to diagnose and fix the issue.
