### ISSUE TITLE
How to change the spawn rates for ores and change items prices from the villager shops? 

### ISSUE THREAD

**Issue by VishwaShah17** [boiscljo/SBA#83]
I wanted to decrease the spawn rates for diamonds and emeralds and wanted to change change some items and their prices from the store. But I can't figure out how to do it from the config. Thanks!

**Comment by boiscljo** [comment]
Spawn rate is in bedwars config. Please refer ro their support.

Changing items in the shop is modifying shop.yml in the plugins/Bedwars folder.
