### ISSUE TITLE
What has changed in the new store file

### ISSUE THREAD

**Issue by yeying-xingchen** [boiscljo/SBA#89]
I want to know where shop.yml and other store files have been modified because I have to translate them and have to re-translate them every time I update them, which is a hassle!

**Comment by boiscljo** [comment]
You can check the file history in shop.yml, they usually don't change much between versions and git will show the difference to the file

**Comment by yeying-xingchen** [comment]
Where?I don't look it in this repo.

**Comment by yeying-xingchen** [comment]
> You can check the file history in shop.yml, they usually don't change much between versions and git will show the difference to the file

Where?i don't look it in this repo.

**Comment by boiscljo** [comment]
https://github.com/boiscljo/SBA/blob/release/plugin/src/main/resources/shops/shop.yml 

There is a button called history top right
